### ISSUE TITLE
List only tags that are applied to child pages

### ISSUE THREAD

**Issue by olivierdalang** [getgrav/grav-plugin-taxonomylist#16]
Hi !

Would it be possible to add an option to list only the tags that are applied to at least one child page ?

I have two different listings, one for blog articles, one for files, and they share the same taxonomy. So it can happen that some tags are applied to some articles, but that there's no file with this tag.

Currently, the taxonomylist plugin still shows a link for those tags, leading to an useless empty page.

Thanks !

Olivier

**Comment by Lamecarlate** [comment]
Hello,

I have the exact same need: I would like to separate "blog articles" from "links", but they share tags & categories. I'm not sure this is possible, however… Taxonomylist is doing its job: take all taxonomies of the site and display them - and not more.

Maybe it would be simpler to write the code ourselves, since it's pretty specific. I'll give it a try.

**Comment by kanduvisla** [comment]
I created a pull request that solves this issue.

**Comment by Lamecarlate** [comment]
Great! I can't wait for it to be included, thanks @kanduvisla !

**Comment by rhukster** [comment]
Merged..
